"use client"

import { useCallback, useEffect, useMemo, useRef, useState } from "react"
import { motion } from "framer-motion"
import { Apple, ChevronDown, ChevronUp, ClipboardList, Coffee, Droplets, Flame, Moon, RefreshCw, Salad, Utensils, Wheat, Zap, type LucideIcon } from "lucide-react"

import { getDietPlan, generateDietPlan, type DietPlan, type DietMeal, type DietFood } from "@/lib/api/guto"
import { ApiError } from "@/lib/api/client"
import { DietPlanValidationError, sanitizeDietPlan } from "@/lib/diet-plan"
import { getLanguage } from "../translations"
import type { ValidLanguage } from "../translations"
import { DietProfileNotice } from "../memory-context/diet-profile-notice"
import { gutoAudio } from "@/lib/audio-haptics"

// ─── Copy ────────────────────────────────────────────────────────────────────

const dietCopy = {
  "pt-BR": {
    title: "DIETA DA SEMANA",
    lockedConfirm: "Esta dieta foi bloqueada pelo supervisor. O GUTO vai tentar recalcular, mas o backend não deve sobrescrever sem liberação.",
    regenerateButton: "REGENERAR DIETA",
    generatingLabel: "GUTO calculando...",
    generatingSubtitle: "Montando sua dieta personalizada...",
    dailyTarget: "META DO DIA",
    perDay: "por dia",
    proteinLabel: "Proteína",
    carbsLabel: "Carbo",
    fatLabel: "Gordura",
    objectiveLabel: "Objetivo",
    foodQuestionLabel: "Dúvida sobre",
    supervisorPlan: "DEFINIDA PELO SUPERVISOR",
    mixedPlan: "EDITADA PELO COACH",
    gutoPlan: "GERADA PELO GUTO",
    lockedPlan: "BLOQUEADA",
    emptyTitle: "Dieta ainda não gerada",
    emptyBody: "Complete seu perfil com altura, peso e país para o GUTO montar seu plano.",
    coachDietTitle: "DIETA DO COACH",
    coachDietBadge: "DEFINIDA PELO COACH",
    coachBreakfast: "Café da manhã",
    coachLunch: "Almoço",
    coachDinner: "Jantar",
    coachSnacks: "Lanches",
    coachHydration: "Hidratação",
    coachNotes: "Observações",
    coachCalories: "kcal estimadas",
    coachProtein: "proteína estimada",
    disclaimer: "Orientação fitness. Não substitui consulta médica ou nutricional.",
    timeoutError: "Ixi, meu sistema demorou demais pra calcular tua dieta. Aguenta aí e tenta de novo.",
    connectionError: "Perdi o fio com o cérebro por um instante. Confere a conexão e me chama de novo.",
    invalidPlanError: "A dieta que voltou do cérebro falhou na checagem final. Não vou mostrar um plano duvidoso. Tente gerar de novo.",
    restrictionError: "Bloqueei essa dieta porque ela trouxe algo que você disse que não come. Gere de novo que eu refaço limpo.",
    locationError: "Bloqueei essa dieta porque ela usou alimento que não bate com onde você mora. Gere de novo que eu mantenho local.",
    calorieError: "Bloqueei essa dieta porque calorias e macros não fecharam com segurança. Gere de novo.",
    goalNames: {
      fat_loss: "Emagrecer",
      muscle_gain: "Hipertrofia",
      conditioning: "Condicionamento",
      mobility_health: "Saúde",
      consistency: "Consistência",
    } as Record<string, string>,
  },
  "en-US": {
    title: "WEEKLY DIET",
    lockedConfirm: "This diet was locked by the supervisor. GUTO will try to recalculate, but the backend should not overwrite without authorization.",
    regenerateButton: "REGENERATE DIET",
    generatingLabel: "GUTO calculating...",
    generatingSubtitle: "Building your personalized plan...",
    dailyTarget: "DAILY TARGET",
    perDay: "per day",
    proteinLabel: "Protein",
    carbsLabel: "Carbs",
    fatLabel: "Fat",
    objectiveLabel: "Goal",
    foodQuestionLabel: "Question about",
    supervisorPlan: "SET BY SUPERVISOR",
    mixedPlan: "EDITED BY COACH",
    gutoPlan: "GENERATED BY GUTO",
    lockedPlan: "LOCKED",
    emptyTitle: "Diet not generated yet",
    emptyBody: "Complete your profile with height, weight and country so GUTO can build your plan.",
    coachDietTitle: "COACH DIET",
    coachDietBadge: "SET BY COACH",
    coachBreakfast: "Breakfast",
    coachLunch: "Lunch",
    coachDinner: "Dinner",
    coachSnacks: "Snacks",
    coachHydration: "Hydration",
    coachNotes: "Notes",
    coachCalories: "estimated kcal",
    coachProtein: "estimated protein",
    disclaimer: "Fitness guidance only. Not a substitute for medical or nutritional advice.",
    timeoutError: "My system took too long to calculate your diet. Hold on and try again.",
    connectionError: "I lost the line to my brain for a moment. Check the connection and call me again.",
    invalidPlanError: "The diet returned by the brain failed the final check. I will not show a doubtful plan. Generate it again.",
    restrictionError: "I blocked this diet because it included something you said you do not eat. Generate it again so I can rebuild it clean.",
    locationError: "I blocked this diet because it used food that does not match where you live. Generate it again and I will keep it local.",
    calorieError: "I blocked this diet because the calories and macros did not close safely. Generate it again.",
    goalNames: {
      fat_loss: "Fat Loss",
      muscle_gain: "Hypertrophy",
      conditioning: "Conditioning",
      mobility_health: "Health",
      consistency: "Consistency",
    } as Record<string, string>,
  },
  "it-IT": {
    title: "DIETA DELLA SETTIMANA",
    lockedConfirm: "Questa dieta è stata bloccata dal supervisore. GUTO proverà a ricalcolare, ma il backend non dovrebbe sovrascrivere senza autorizzazione.",
    regenerateButton: "RIGENERA DIETA",
    generatingLabel: "GUTO sta calcolando...",
    generatingSubtitle: "Creando il tuo piano personale...",
    dailyTarget: "OBIETTIVO GIORNALIERO",
    perDay: "al giorno",
    proteinLabel: "Proteine",
    carbsLabel: "Carboidrati",
    fatLabel: "Grassi",
    objectiveLabel: "Obiettivo",
    foodQuestionLabel: "Dubbio su",
    supervisorPlan: "DEFINITA DAL SUPERVISORE",
    mixedPlan: "MODIFICATA DAL COACH",
    gutoPlan: "GENERATA DA GUTO",
    lockedPlan: "BLOCCATA",
    emptyTitle: "Dieta non ancora creata",
    emptyBody: "Completa il profilo con altezza, peso e paese per far creare la dieta a GUTO.",
    coachDietTitle: "DIETA DEL COACH",
    coachDietBadge: "DEFINITA DAL COACH",
    coachBreakfast: "Colazione",
    coachLunch: "Pranzo",
    coachDinner: "Cena",
    coachSnacks: "Spuntini",
    coachHydration: "Idratazione",
    coachNotes: "Note",
    coachCalories: "kcal stimate",
    coachProtein: "proteine stimate",
    disclaimer: "Solo orientamento fitness. Non sostituisce la consulenza medica o nutrizionale.",
    timeoutError: "Il mio sistema ci ha messo troppo a calcolare la tua dieta. Aspetta un attimo e riprova.",
    connectionError: "Ho perso il filo col mio cervello per un attimo. Controlla la connessione e richiamami.",
    invalidPlanError: "La dieta tornata dal cervello non ha superato il controllo finale. Non mostro un piano dubbio. Generala di nuovo.",
    restrictionError: "Ho bloccato questa dieta perché includeva qualcosa che hai detto di non mangiare. Rigenerala così la rifaccio pulita.",
    locationError: "Ho bloccato questa dieta perché usava alimenti che non battono con dove vivi. Rigenerala e la tengo locale.",
    calorieError: "Ho bloccato questa dieta perché calorie e macro non tornavano in sicurezza. Rigenerala.",
    goalNames: {
      fat_loss: "Dimagrire",
      muscle_gain: "Ipertrofia",
      conditioning: "Condizionamento",
      mobility_health: "Salute",
      consistency: "Costanza",
    } as Record<string, string>,
  },
} as const

const MEAL_ICON: Record<string, LucideIcon> = {
  cafe: Coffee,
  lanche1: Apple,
  almoco: Utensils,
  lanche2: Apple,
  jantar: Moon,
}

// ─── Props ────────────────────────────────────────────────────────────────────

interface DietTabProps {
  userId: string
  language: string
  onFoodDoubt: (food: DietFood, meal: DietMeal) => void
  memory: import("@/lib/api/guto").GutoMemory | null
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function getWeekRange(generatedAt: string, language: ValidLanguage): string {
  const start = new Date(generatedAt)
  start.setHours(0, 0, 0, 0)
  const end = new Date(start)
  end.setDate(start.getDate() + 6)
  const fmt = (d: Date) =>
    d.toLocaleDateString(language, { day: "2-digit", month: "2-digit", year: "numeric" })
  return `${fmt(start)} – ${fmt(end)}`
}

function isMissingProfileError(error: unknown) {
  if (typeof error !== "object" || error === null || !("details" in error)) return false
  const details = (error as { details?: unknown }).details
  return typeof details === "object" && details !== null && (details as { error?: unknown }).error === "missing_profile_fields"
}

function getDietFailureReason(error: unknown) {
  if (!(error instanceof ApiError)) return null
  const details = error.details
  if (typeof details !== "object" || details === null) return null
  const reason = (details as { reason?: unknown }).reason
  return typeof reason === "string" ? reason : null
}

function getDietErrorMessage(
  error: unknown,
  copy: {
    timeoutError: string
    connectionError: string
    invalidPlanError: string
    restrictionError: string
    locationError: string
    calorieError: string
  }
): string {
  if (error instanceof DietPlanValidationError) return copy.invalidPlanError
  if (error instanceof ApiError) {
    if (error.code === "TIMEOUT") return copy.timeoutError
    if (error.code === "CONNECTION_ERROR") return copy.connectionError
    const reason = getDietFailureReason(error)
    if (reason === "food_restriction") return copy.restrictionError
    if (reason === "location") return copy.locationError
    if (reason === "calorie_validation") return copy.calorieError
    return error.message
  }
  return error instanceof Error ? error.message : copy.connectionError
}

// ─── Meal Card ────────────────────────────────────────────────────────────────

function MealCard({
  meal,
  onFoodDoubt,
  index,
  foodQuestionLabel,
}: {
  meal: DietMeal
  onFoodDoubt: (food: DietFood, meal: DietMeal) => void
  index: number
  foodQuestionLabel: string
}) {
  const [expanded, setExpanded] = useState(false)
  const cardRef = useRef<HTMLDivElement | null>(null)
  const MealIcon = MEAL_ICON[meal.id] ?? Salad

  useEffect(() => {
    if (!expanded) return
    window.setTimeout(() => {
      cardRef.current?.scrollIntoView({ behavior: "smooth", block: "nearest" })
    }, 80)
  }, [expanded])

  return (
    <motion.div
      ref={cardRef}
      className="guto-premium-card"
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.05, duration: 0.22 }}
    >
      {/* Header row — always visible */}
      <button
        type="button"
        onClick={() => { gutoAudio.playGutoFeedback('tap'); setExpanded((v) => !v) }}
        className="flex w-full items-center gap-3 px-3.5 py-3.5 text-left"
        aria-expanded={expanded}
      >
        <span className="guto-slot grid h-11 w-11 shrink-0 place-items-center rounded-full text-(--guto-cyan)">
          <MealIcon className="h-5 w-5" />
        </span>

        {/* Time */}
        <span className="guto-readable-label shrink-0 text-(--guto-cyan)">
          {meal.time}
        </span>

        {/* Name */}
        <h2 className="min-w-0 flex-1 wrap-break-word text-left text-[15px] font-black uppercase leading-tight tracking-[0.02em] text-(--guto-navy)">
          {meal.name}
        </h2>

        {/* Total kcal + chevron */}
        <div className="flex items-center gap-1.5 shrink-0">
          <span className="font-mono text-[13px] font-black text-(--guto-navy)/70">
            {meal.totalKcal}
            <span className="ml-0.5 text-[9px] font-bold text-(--guto-navy)/42">kcal</span>
          </span>
          {expanded
            ? <ChevronUp className="h-3.5 w-3.5 text-(--guto-cyan)" />
            : <ChevronDown className="h-3.5 w-3.5 text-[rgba(13,35,65,0.28)]" />
          }
        </div>
      </button>

      {/* Expanded body — CSS max-height transition, safe on iOS Safari */}
      {expanded && (
        <motion.div
          initial={{ opacity: 0, y: -4 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.18 }}
        >
          <div className="mx-3.5 h-px bg-[rgba(82,231,255,0.18)]" />

          <div className="px-3.5 pt-2.5 pb-3 flex flex-col gap-0">
          {/* Food rows */}
          {meal.foods.map((food, i) => (
            <div
              key={i}
              className="grid grid-cols-[minmax(0,1fr)_auto_auto] items-center gap-x-2 gap-y-1 border-b border-[rgba(13,35,65,0.06)] py-2.5 last:border-0 max-[360px]:grid-cols-[minmax(0,1fr)_auto]"
            >
              {/* Food name */}
              <span className="guto-readable-body min-w-0 wrap-break-word">
                {food.name}
              </span>

              {/* Quantity badge */}
              <span className="guto-status-pill justify-self-end whitespace-nowrap text-(--guto-navy)/60 max-[360px]:col-start-1 max-[360px]:row-start-2 max-[360px]:justify-self-start">
                {food.quantity}
              </span>

              {/* ? button — per food item */}
              <button
                type="button"
                onClick={(e) => {
                  e.stopPropagation()
                  gutoAudio.playGutoFeedback('tap')
                  onFoodDoubt(food, meal)
                }}
                aria-label={`${foodQuestionLabel} ${food.name}`}
                className="guto-big-touch flex items-center justify-center rounded-full border border-[rgba(82,231,255,0.45)] bg-[rgba(82,231,255,0.10)] text-[15px] font-black text-(--guto-cyan) transition-transform active:scale-90 max-[360px]:col-start-2 max-[360px]:row-span-2"
              >
                ?
              </button>
            </div>
          ))}

          {/* Guto note */}
          {meal.gutoNote && (
            <p className="guto-readable-body pt-2 text-[12px] italic">
              <span className="not-italic font-black text-(--guto-cyan) mr-1">GUTO</span>
              {meal.gutoNote}
            </p>
          )}
          </div>
        </motion.div>
      )}
    </motion.div>
  )
}

// ─── Coach Diet View ─────────────────────────────────────────────────────────

type CoachDietDay = {
  breakfast?: string
  lunch?: string
  dinner?: string
  snacks?: string
  notes?: string
  hydration?: string
  caloriesEstimate?: number
  proteinEstimate?: number
}

interface CoachDietCopy {
  coachDietTitle: string
  coachDietBadge: string
  coachBreakfast: string
  coachLunch: string
  coachDinner: string
  coachSnacks: string
  coachHydration: string
  coachNotes: string
  coachCalories: string
  coachProtein: string
}

function CoachMealCard({ icon: Icon, label, text, index }: { icon: LucideIcon; label: string; text: string; index: number }) {
  return (
    <motion.div
      className="guto-premium-card px-3.5 py-3"
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.05, duration: 0.22 }}
    >
      <div className="flex items-start gap-3">
        <span className="guto-slot mt-0.5 grid h-11 w-11 shrink-0 place-items-center rounded-full text-(--guto-cyan)">
          <Icon className="h-5 w-5" />
        </span>
        <div className="min-w-0 flex-1">
          <h3 className="guto-readable-label mb-1 text-(--guto-cyan)">{label}</h3>
          <p className="guto-readable-body whitespace-pre-wrap">{text}</p>
        </div>
      </div>
    </motion.div>
  )
}

function CoachDietView({ coachDiet, copy }: { coachDiet: CoachDietDay; copy: CoachDietCopy }) {
  const meals = [
    { key: "breakfast", icon: Coffee, label: copy.coachBreakfast, text: coachDiet.breakfast },
    { key: "lunch", icon: Utensils, label: copy.coachLunch, text: coachDiet.lunch },
    { key: "dinner", icon: Moon, label: copy.coachDinner, text: coachDiet.dinner },
    { key: "snacks", icon: Apple, label: copy.coachSnacks, text: coachDiet.snacks },
  ].filter((m): m is { key: string; icon: LucideIcon; label: string; text: string } => Boolean(m.text))

  return (
    <div className="guto-tab-shell">
      <div className="guto-tab-header">
        <h1 className="guto-tab-title">
          {copy.coachDietTitle}
        </h1>
        <div className="mt-2 flex items-center justify-center">
          <span className="guto-status-pill">
            {copy.coachDietBadge}
          </span>
        </div>
      </div>

      {(coachDiet.caloriesEstimate || coachDiet.proteinEstimate) && (
        <motion.div
          className="guto-premium-card mb-3 flex shrink-0 items-center px-4 py-3"
          initial={{ opacity: 0, y: -6 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.28 }}
        >
          {coachDiet.caloriesEstimate && (
            <div className="flex flex-col items-center gap-0.5 flex-1">
              <Flame className="h-3 w-3 text-(--guto-cyan)" />
              <span className="text-[14px] font-black leading-none text-(--guto-navy)">{coachDiet.caloriesEstimate}</span>
              <span className="font-mono text-[7px] uppercase tracking-widest text-[rgba(13,35,65,0.38)] mt-0.5">{copy.coachCalories}</span>
            </div>
          )}
          {coachDiet.caloriesEstimate && coachDiet.proteinEstimate && (
            <div className="w-px h-6 bg-[rgba(13,35,65,0.07)]" />
          )}
          {coachDiet.proteinEstimate && (
            <div className="flex flex-col items-center gap-0.5 flex-1">
              <Zap className="h-3 w-3 text-(--guto-cyan)" />
              <span className="text-[14px] font-black leading-none text-(--guto-navy)">{coachDiet.proteinEstimate}g</span>
              <span className="font-mono text-[7px] uppercase tracking-widest text-[rgba(13,35,65,0.38)] mt-0.5">{copy.coachProtein}</span>
            </div>
          )}
        </motion.div>
      )}

      <div className="guto-tab-scroll flex flex-col gap-2.5 pb-[calc(8rem+env(safe-area-inset-bottom))] scroll-pb-[calc(8rem+env(safe-area-inset-bottom))]">
        {meals.map((m, i) => (
          <CoachMealCard key={m.key} icon={m.icon} label={m.label} text={m.text} index={i} />
        ))}

        {coachDiet.hydration && (
          <motion.div
            className="guto-premium-card flex items-start gap-3 px-3.5 py-3"
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: meals.length * 0.05, duration: 0.22 }}
          >
            <span className="guto-slot mt-0.5 grid h-11 w-11 shrink-0 place-items-center rounded-full text-(--guto-cyan)">
              <Droplets className="h-5 w-5" />
            </span>
            <div className="min-w-0 flex-1">
              <h3 className="guto-readable-label mb-1 text-(--guto-cyan)">{copy.coachHydration}</h3>
              <p className="guto-readable-body">{coachDiet.hydration}</p>
            </div>
          </motion.div>
        )}

        {coachDiet.notes && (
          <motion.div
            className="guto-premium-card flex items-start gap-3 px-3.5 py-3"
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: (meals.length + (coachDiet.hydration ? 1 : 0)) * 0.05, duration: 0.22 }}
          >
            <span className="guto-slot mt-0.5 grid h-11 w-11 shrink-0 place-items-center rounded-full text-(--guto-cyan)">
              <ClipboardList className="h-5 w-5" />
            </span>
            <div className="min-w-0 flex-1">
              <h3 className="guto-readable-label mb-1 text-(--guto-cyan)">{copy.coachNotes}</h3>
              <p className="guto-readable-body italic">{coachDiet.notes}</p>
            </div>
          </motion.div>
        )}
      </div>
    </div>
  )
}

// ─── Main component ───────────────────────────────────────────────────────────

export function DietTab({ userId, language, onFoodDoubt, memory }: DietTabProps) {
  const validLang = getLanguage(language)
  const copy = dietCopy[validLang]

  const [plan, setPlan] = useState<DietPlan | null>(null)
  const [status, setStatus] = useState<"loading" | "generating" | "error" | "ready">("loading")
  const [errorMsg, setErrorMsg] = useState<string | null>(null)
  const [retrying, setRetrying] = useState(false)
  const latestMemoryRef = useRef(memory)

  const weekDaysOrder = ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"] as const
  const todayCoachDiet = memory?.weeklyDietPlan?.days?.[weekDaysOrder[new Date().getDay()]] ?? null
  const dietProfileKey = useMemo(() => JSON.stringify({
    heightCm: memory?.heightCm ?? null,
    weightKg: memory?.weightKg ?? null,
    trainingGoal: memory?.trainingGoal ?? null,
    biologicalSex: memory?.biologicalSex ?? null,
    userAge: memory?.userAge ?? null,
    trainingLevel: memory?.trainingLevel ?? null,
    trainingStatus: memory?.trainingStatus ?? null,
    foodRestrictions: memory?.foodRestrictions ?? null,
    country: memory?.country ?? null,
    countryCode: memory?.countryCode ?? null,
  }), [
    memory?.heightCm,
    memory?.weightKg,
    memory?.trainingGoal,
    memory?.biologicalSex,
    memory?.userAge,
    memory?.trainingLevel,
    memory?.trainingStatus,
    memory?.foodRestrictions,
    memory?.country,
    memory?.countryCode,
  ])

  useEffect(() => {
    latestMemoryRef.current = memory
  }, [memory])

  function isPlanStale(generatedAt: string): boolean {
    const planDate = new Date(generatedAt)
    const now = new Date()
    const lastSunday = new Date(now)
    lastSunday.setDate(now.getDate() - now.getDay())
    lastSunday.setHours(0, 0, 0, 0)
    return planDate < lastSunday
  }

  const isProfileCompleteFor = useCallback((profile: typeof memory): boolean => {
    if (!profile) return false
    return Boolean(
      profile.heightCm && profile.heightCm > 0 &&
      profile.weightKg && profile.weightKg > 0 &&
      profile.trainingGoal &&
      profile.biologicalSex &&
      profile.userAge &&
      (profile.trainingLevel || profile.trainingStatus) &&
      profile.country &&
      profile.countryCode
    )
  }, [])

  function isProfileComplete(): boolean {
    return isProfileCompleteFor(memory)
  }

  useEffect(() => {
    if (!userId) return
    // If coach defined today's diet, skip API call
    if (todayCoachDiet) {
      setStatus("ready")
      return
    }
    let cancelled = false

    const hardTimeout = setTimeout(() => {
      if (!cancelled) {
        cancelled = true
        setStatus("error")
        setErrorMsg(copy.timeoutError)
      }
    }, 30_000)

    const run = async () => {
      setStatus("loading")
      setErrorMsg(null)
      try {
        let fetched = await getDietPlan()
        if (cancelled) return

        if (fetched && isPlanStale(fetched.generatedAt)) fetched = null

        if (!fetched) {
          if (!isProfileCompleteFor(latestMemoryRef.current)) {
            setPlan(null)
            setStatus("error")
            setErrorMsg(null)
            return
          }
          setStatus("generating")
          fetched = await generateDietPlan(validLang)
          if (cancelled) return
        }

        setPlan(sanitizeDietPlan(fetched, latestMemoryRef.current))
        setStatus("ready")
      } catch (err: unknown) {
        if (cancelled) return
        setPlan(null)
        setStatus("error")
        if (!isMissingProfileError(err)) {
          setErrorMsg(getDietErrorMessage(err, copy))
        }
      } finally {
        clearTimeout(hardTimeout)
      }
    }

    void run()
    return () => {
      cancelled = true
      clearTimeout(hardTimeout)
    }
  }, [userId, validLang, dietProfileKey, copy, isProfileCompleteFor, todayCoachDiet])

  const handleRetry = async () => {
    if (retrying) return
    if (plan?.lockedByCoach) {
      const confirmed = window.confirm(copy.lockedConfirm)
      if (!confirmed) return
    }
    setRetrying(true)
    setErrorMsg(null)
    try {
      if (!isProfileCompleteFor(latestMemoryRef.current)) {
        setPlan(null)
        setStatus("error")
        setErrorMsg(null)
        return
      }
      const newPlan = await generateDietPlan(validLang)
      setPlan(sanitizeDietPlan(newPlan, latestMemoryRef.current))
      setStatus("ready")
    } catch (err: unknown) {
      setStatus("error")
      setErrorMsg(getDietErrorMessage(err, copy))
    } finally {
      setRetrying(false)
    }
  }

  const retryLabel: Record<ValidLanguage, string> = {
    "pt-BR": "Falha ao gerar. Tente novamente.",
    "en-US": "Failed to generate. Try again.",
    "it-IT": "Errore nella creazione. Riprova.",
  }

  // ── Coach weekly diet takes priority over AI-generated plan ─────────────
  if (todayCoachDiet) {
    return <CoachDietView coachDiet={todayCoachDiet} copy={copy} />
  }

  // ── Loading / Generating ──────────────────────────────────────────────────
  if (status === "loading" || status === "generating") {
    return (
      <div className="flex h-full min-h-0 flex-col items-center justify-center gap-3">
        <motion.div
          animate={{ opacity: [0.4, 1, 0.4] }}
          transition={{ duration: 1.5, repeat: Infinity }}
          className="font-mono text-[10px] uppercase tracking-[0.22em] text-(--guto-cyan)"
        >
          {copy.generatingLabel}
        </motion.div>
        {status === "generating" && (
          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.6 }}
            className="font-mono text-[8px] uppercase tracking-[0.14em] text-[rgba(13,35,65,0.35)] text-center max-w-[200px]"
          >
            {copy.generatingSubtitle}
          </motion.p>
        )}
      </div>
    )
  }

  // ── Empty / Error ─────────────────────────────────────────────────────────
  if (!plan) {
    const profileComplete = isProfileComplete()
    const bodyText = !profileComplete ? copy.emptyBody : errorMsg || retryLabel[validLang]

    return (
      <div className="guto-tab-shell">
        <div className="guto-tab-header">
          <h1 className="guto-tab-title">
            {copy.title}
          </h1>
        </div>
        <div className="flex-1 flex flex-col items-center justify-center gap-5 pb-4">
          <div className="relative flex h-20 w-20 items-center justify-center">
            <div className="absolute inset-0 rounded-full bg-[rgba(82,231,255,0.10)] blur-xl" />
            <motion.div
              animate={{ rotate: [0, 8, -8, 0], scale: [1, 1.04, 1] }}
              transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }}
              className="guto-slot relative grid h-16 w-16 place-items-center rounded-full text-(--guto-cyan)"
            >
              <Salad className="h-8 w-8" />
            </motion.div>
          </div>
          <div className="text-center max-w-[240px]">
            <h2 className="mb-2 text-[1.05rem] font-black uppercase leading-tight tracking-[0.04em] text-(--guto-navy)">
              {copy.emptyTitle}
            </h2>
            <p className="guto-readable-body">{bodyText}</p>
          </div>
          {profileComplete && status === "error" && (
            <motion.button
              type="button"
              whileTap={{ scale: 0.97 }}
              onClick={() => { gutoAudio.playGutoFeedback("tap"); void handleRetry() }}
              disabled={retrying}
              className="guto-secondary-button min-w-[180px]"
            >
              {retrying ? copy.generatingLabel : copy.regenerateButton}
            </motion.button>
          )}
        </div>
      </div>
    )
  }

  // ── Plan view ─────────────────────────────────────────────────────────────
  const { macros, meals, generatedAt } = plan
  const goalName = copy.goalNames[macros.goal] || macros.goal
  const weekRange = getWeekRange(generatedAt, validLang)
  const planSourceLabel =
    plan.source === "coach_manual"
      ? copy.supervisorPlan
      : plan.source === "mixed"
        ? copy.mixedPlan
        : plan.source === "guto_generated"
          ? copy.gutoPlan
          : null

  return (
    <div className="guto-tab-shell">

      {/* ── Header ── */}
      <div className="guto-tab-header">
        <h1 className="guto-tab-title">
          {copy.title}
        </h1>
        <p className="guto-readable-label mt-2">
          {weekRange}
        </p>
        {(planSourceLabel || plan.lockedByCoach) && (
          <div className="mt-2 flex flex-wrap items-center justify-center gap-1.5">
            {planSourceLabel && (
              <span className="guto-status-pill">
                {planSourceLabel}
              </span>
            )}
            {plan.lockedByCoach && (
              <span className="guto-status-pill bg-[rgba(13,35,65,0.08)] text-[rgba(13,35,65,0.58)]">
                {copy.lockedPlan}
              </span>
            )}
          </div>
        )}
      </div>

      {/* ── Summary card ── */}
      <motion.div
        className="guto-premium-card mb-3 shrink-0"
        initial={{ opacity: 0, y: -6 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.28 }}
      >
        {/* Kcal row */}
        <div className="flex items-center justify-between px-4 pb-2 pt-3.5">
          <div className="flex items-end gap-1.5">
            <Flame className="h-4 w-4 text-(--guto-cyan) mb-px shrink-0" />
            <span className="text-[24px] font-black leading-none text-(--guto-navy)">
              {macros.targetKcal}
            </span>
            <div className="flex flex-col mb-0.5">
              <span className="font-mono text-[8px] leading-none text-(--guto-navy)/40">kcal</span>
              <span className="font-mono text-[7px] leading-none text-(--guto-navy)/30">{copy.perDay}</span>
            </div>
          </div>
          <span className="guto-status-pill text-(--guto-navy)">
            {goalName}
          </span>
        </div>

        {/* Divider */}
        <div className="mx-4 h-px bg-[rgba(82,231,255,0.15)]" />

        {/* Macros row */}
        <div className="flex items-center px-4 py-2.5">
          <MacroPill icon={<Zap className="h-3 w-3" />} label={copy.proteinLabel} value={`${macros.proteinG}g`} color="cyan" />
          <div className="w-px h-6 bg-[rgba(13,35,65,0.07)]" />
          <MacroPill icon={<Wheat className="h-3 w-3" />} label={copy.carbsLabel} value={`${macros.carbsG}g`} color="amber" />
          <div className="w-px h-6 bg-[rgba(13,35,65,0.07)]" />
          <MacroPill icon={<Droplets className="h-3 w-3" />} label={copy.fatLabel} value={`${macros.fatG}g`} color="sky" />
        </div>
      </motion.div>

      {/* Perfil usado na dieta — memória visível (Fase 3K) */}
      <DietProfileNotice memory={memory} language={validLang} />

      {/* ── Scrollable meals ── */}
      <div className="guto-tab-scroll flex flex-col gap-2.5 pb-[calc(8rem+env(safe-area-inset-bottom))] scroll-pb-[calc(8rem+env(safe-area-inset-bottom))]">
        {meals.map((meal, i) => (
          <MealCard
            key={meal.id}
            meal={meal}
            onFoodDoubt={onFoodDoubt}
            index={i}
            foodQuestionLabel={copy.foodQuestionLabel}
          />
        ))}

        {/* Regenerate — subtle, at bottom */}
        <motion.button
          type="button"
          whileTap={{ scale: 0.97 }}
          onClick={() => { gutoAudio.playGutoFeedback('tap'); handleRetry() }}
          disabled={retrying}
          className="guto-cta-ghost mt-1 disabled:opacity-40"
        >
          <RefreshCw className="h-3 w-3" />
          {copy.regenerateButton}
        </motion.button>

        <p className="guto-readable-label mt-2 px-4 text-center text-[8px] text-[rgba(13,35,65,0.38)]">
          {copy.disclaimer}
        </p>
      </div>
    </div>
  )
}

// ─── MacroPill ─────────────────────────────────────────────────────────────────

function MacroPill({
  icon,
  label,
  value,
  color,
}: {
  icon: React.ReactNode
  label: string
  value: string
  color: "cyan" | "amber" | "sky"
}) {
  const colorMap = { cyan: "text-(--guto-cyan)", amber: "text-amber-500", sky: "text-sky-400" }
  return (
    <div className="flex flex-1 flex-col items-center gap-0.5">
      <div className={colorMap[color]}>{icon}</div>
      <span className="text-[15px] font-black leading-none text-(--guto-navy)">{value}</span>
      <span className="guto-readable-label mt-0.5 text-[8px]">{label}</span>
    </div>
  )
}
