"use client"

import { useEffect, useRef, useState } from "react"
import { motion } from "framer-motion"
import { Flame, Zap, Wheat, Droplets, RefreshCw, ChevronDown, ChevronUp } from "lucide-react"

import { getDietPlan, generateDietPlan, type DietPlan, type DietMeal, type DietFood } from "@/lib/api/guto"
import { sanitizeDietPlan } from "@/lib/diet-plan"
import { getLanguage } from "../translations"
import type { ValidLanguage } from "../translations"
import { gutoAudio } from "@/lib/audio-haptics"

// ─── Copy ────────────────────────────────────────────────────────────────────

const dietCopy = {
  "pt-BR": {
    title: "DIETA DA SEMANA",
    lockedConfirm: "Esta dieta foi bloqueada pelo supervisor. O GUTO vai tentar recalcular, mas o backend não deve sobrescrever sem liberação.",
    regenerateButton: "REGENERAR DIETA",
    generatingLabel: "GUTO calculando...",
    generatingSubtitle: "Montando sua dieta personalizada...",
    dailyTarget: "META DO DIA",
    perDay: "por dia",
    proteinLabel: "Proteína",
    carbsLabel: "Carbo",
    fatLabel: "Gordura",
    objectiveLabel: "Objetivo",
    foodQuestionLabel: "Dúvida sobre",
    supervisorPlan: "DEFINIDA PELO SUPERVISOR",
    mixedPlan: "EDITADA PELO COACH",
    gutoPlan: "GERADA PELO GUTO",
    lockedPlan: "BLOQUEADA",
    emptyTitle: "Dieta ainda não gerada",
    emptyBody: "Complete seu perfil com altura, peso e país para o GUTO montar seu plano.",
    coachDietTitle: "DIETA DO COACH",
    coachDietBadge: "DEFINIDA PELO COACH",
    coachBreakfast: "Café da manhã",
    coachLunch: "Almoço",
    coachDinner: "Jantar",
    coachSnacks: "Lanches",
    coachHydration: "Hidratação",
    coachNotes: "Observações",
    coachCalories: "kcal estimadas",
    coachProtein: "proteína estimada",
    disclaimer: "Orientação fitness. Não substitui consulta médica ou nutricional.",
    goalNames: {
      fat_loss: "Emagrecer",
      muscle_gain: "Hipertrofia",
      conditioning: "Condicionamento",
      mobility_health: "Saúde",
      consistency: "Consistência",
    } as Record<string, string>,
  },
  "en-US": {
    title: "WEEKLY DIET",
    lockedConfirm: "This diet was locked by the supervisor. GUTO will try to recalculate, but the backend should not overwrite without authorization.",
    regenerateButton: "REGENERATE DIET",
    generatingLabel: "GUTO calculating...",
    generatingSubtitle: "Building your personalized plan...",
    dailyTarget: "DAILY TARGET",
    perDay: "per day",
    proteinLabel: "Protein",
    carbsLabel: "Carbs",
    fatLabel: "Fat",
    objectiveLabel: "Goal",
    foodQuestionLabel: "Question about",
    supervisorPlan: "SET BY SUPERVISOR",
    mixedPlan: "EDITED BY COACH",
    gutoPlan: "GENERATED BY GUTO",
    lockedPlan: "LOCKED",
    emptyTitle: "Diet not generated yet",
    emptyBody: "Complete your profile with height, weight and country so GUTO can build your plan.",
    coachDietTitle: "COACH DIET",
    coachDietBadge: "SET BY COACH",
    coachBreakfast: "Breakfast",
    coachLunch: "Lunch",
    coachDinner: "Dinner",
    coachSnacks: "Snacks",
    coachHydration: "Hydration",
    coachNotes: "Notes",
    coachCalories: "estimated kcal",
    coachProtein: "estimated protein",
    disclaimer: "Fitness guidance only. Not a substitute for medical or nutritional advice.",
    goalNames: {
      fat_loss: "Fat Loss",
      muscle_gain: "Hypertrophy",
      conditioning: "Conditioning",
      mobility_health: "Health",
      consistency: "Consistency",
    } as Record<string, string>,
  },
  "it-IT": {
    title: "DIETA DELLA SETTIMANA",
    lockedConfirm: "Questa dieta è stata bloccata dal supervisore. GUTO proverà a ricalcolare, ma il backend non dovrebbe sovrascrivere senza autorizzazione.",
    regenerateButton: "RIGENERA DIETA",
    generatingLabel: "GUTO sta calcolando...",
    generatingSubtitle: "Creando il tuo piano personale...",
    dailyTarget: "OBIETTIVO GIORNALIERO",
    perDay: "al giorno",
    proteinLabel: "Proteine",
    carbsLabel: "Carboidrati",
    fatLabel: "Grassi",
    objectiveLabel: "Obiettivo",
    foodQuestionLabel: "Dubbio su",
    supervisorPlan: "DEFINITA DAL SUPERVISORE",
    mixedPlan: "MODIFICATA DAL COACH",
    gutoPlan: "GENERATA DA GUTO",
    lockedPlan: "BLOCCATA",
    emptyTitle: "Dieta non ancora creata",
    emptyBody: "Completa il profilo con altezza, peso e paese per far creare la dieta a GUTO.",
    coachDietTitle: "DIETA DEL COACH",
    coachDietBadge: "DEFINITA DAL COACH",
    coachBreakfast: "Colazione",
    coachLunch: "Pranzo",
    coachDinner: "Cena",
    coachSnacks: "Spuntini",
    coachHydration: "Idratazione",
    coachNotes: "Note",
    coachCalories: "kcal stimate",
    coachProtein: "proteine stimate",
    disclaimer: "Solo orientamento fitness. Non sostituisce la consulenza medica o nutrizionale.",
    goalNames: {
      fat_loss: "Dimagrire",
      muscle_gain: "Ipertrofia",
      conditioning: "Condizionamento",
      mobility_health: "Salute",
      consistency: "Costanza",
    } as Record<string, string>,
  },
} as const

// Emoji per meal ID
const MEAL_EMOJI: Record<string, string> = {
  cafe: "☕",
  lanche1: "🍎",
  almoco: "🍽️",
  lanche2: "🥜",
  jantar: "🌙",
}

// ─── Props ────────────────────────────────────────────────────────────────────

interface DietTabProps {
  userId: string
  language: string
  onFoodDoubt: (food: DietFood, meal: DietMeal) => void
  memory: import("@/lib/api/guto").GutoMemory | null
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function getWeekRange(generatedAt: string, language: ValidLanguage): string {
  const start = new Date(generatedAt)
  start.setHours(0, 0, 0, 0)
  const end = new Date(start)
  end.setDate(start.getDate() + 6)
  const fmt = (d: Date) =>
    d.toLocaleDateString(language, { day: "2-digit", month: "2-digit", year: "numeric" })
  return `${fmt(start)} – ${fmt(end)}`
}

function isMissingProfileError(error: unknown) {
  if (typeof error !== "object" || error === null || !("details" in error)) return false
  const details = (error as { details?: unknown }).details
  return typeof details === "object" && details !== null && (details as { error?: unknown }).error === "missing_profile_fields"
}

function getDietErrorMessage(error: unknown) {
  return error instanceof Error ? error.message : "Erro ao gerar dieta."
}

// ─── Meal Card ────────────────────────────────────────────────────────────────

function MealCard({
  meal,
  onFoodDoubt,
  index,
  foodQuestionLabel,
}: {
  meal: DietMeal
  onFoodDoubt: (food: DietFood, meal: DietMeal) => void
  index: number
  foodQuestionLabel: string
}) {
  const [expanded, setExpanded] = useState(false)
  const cardRef = useRef<HTMLDivElement | null>(null)
  const emoji = MEAL_EMOJI[meal.id] ?? "🥗"

  useEffect(() => {
    if (!expanded) return
    window.setTimeout(() => {
      cardRef.current?.scrollIntoView({ behavior: "smooth", block: "nearest" })
    }, 80)
  }, [expanded])

  return (
    <motion.div
      ref={cardRef}
      className="rounded-[1.1rem] border border-white/60 bg-white/30"
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.05, duration: 0.22 }}
    >
      {/* Header row — always visible */}
      <button
        type="button"
        onClick={() => { gutoAudio.playGutoFeedback('tap'); setExpanded((v) => !v) }}
        className="w-full flex items-center gap-2.5 px-3.5 py-3"
        aria-expanded={expanded}
      >
        {/* Emoji */}
        <span className="text-[16px] shrink-0">{emoji}</span>

        {/* Time */}
        <span className="font-mono text-[9px] font-black tracking-[0.06em] text-[var(--guto-cyan)] shrink-0">
          {meal.time}
        </span>

        {/* Name */}
        <h2 className="min-w-0 flex-1 break-words text-left text-[12px] font-black uppercase leading-tight tracking-[0.05em] text-[var(--guto-navy)]">
          {meal.name}
        </h2>

        {/* Total kcal + chevron */}
        <div className="flex items-center gap-1.5 shrink-0">
          <span className="font-mono text-[11px] font-black text-[var(--guto-navy)]/55">
            {meal.totalKcal}
            <span className="text-[8px] font-normal ml-0.5 text-[var(--guto-navy)]/35">kcal</span>
          </span>
          {expanded
            ? <ChevronUp className="h-3.5 w-3.5 text-[var(--guto-cyan)]" />
            : <ChevronDown className="h-3.5 w-3.5 text-[rgba(13,35,65,0.28)]" />
          }
        </div>
      </button>

      {/* Expanded body — CSS max-height transition, safe on iOS Safari */}
      {expanded && (
        <motion.div
          initial={{ opacity: 0, y: -4 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.18 }}
        >
          <div className="mx-3.5 h-px bg-[rgba(82,231,255,0.18)]" />

          <div className="px-3.5 pt-2.5 pb-3 flex flex-col gap-0">
          {/* Food rows */}
          {meal.foods.map((food, i) => (
            <div
              key={i}
              className="grid grid-cols-[minmax(0,1fr)_auto_auto] items-center gap-x-2 gap-y-1 py-2 border-b border-[rgba(13,35,65,0.06)] last:border-0 max-[360px]:grid-cols-[minmax(0,1fr)_auto]"
            >
              {/* Food name */}
              <span className="min-w-0 break-words text-[12px] leading-snug text-[var(--guto-navy)]/85">
                {food.name}
              </span>

              {/* Quantity badge */}
              <span className="justify-self-end font-mono text-[9px] font-black text-[var(--guto-navy)]/50 bg-[rgba(82,231,255,0.12)] px-2 py-0.5 rounded-full whitespace-nowrap max-[360px]:col-start-1 max-[360px]:row-start-2 max-[360px]:justify-self-start">
                {food.quantity}
              </span>

              {/* ? button — per food item */}
              <button
                type="button"
                onClick={(e) => {
                  e.stopPropagation()
                  gutoAudio.playGutoFeedback('tap')
                  onFoodDoubt(food, meal)
                }}
                aria-label={`${foodQuestionLabel} ${food.name}`}
                className="h-7 w-7 rounded-full border border-[rgba(82,231,255,0.45)] bg-[rgba(82,231,255,0.10)] text-[var(--guto-cyan)] font-black text-[12px] flex items-center justify-center active:scale-90 transition-transform touch-manipulation max-[360px]:col-start-2 max-[360px]:row-span-2"
              >
                ?
              </button>
            </div>
          ))}

          {/* Guto note */}
          {meal.gutoNote && (
            <p className="text-[10px] leading-snug text-[rgba(13,35,65,0.50)] italic pt-2">
              <span className="not-italic font-black text-[var(--guto-cyan)] mr-1">GUTO</span>
              {meal.gutoNote}
            </p>
          )}
          </div>
        </motion.div>
      )}
    </motion.div>
  )
}

// ─── Coach Diet View ─────────────────────────────────────────────────────────

type CoachDietDay = {
  breakfast?: string
  lunch?: string
  dinner?: string
  snacks?: string
  notes?: string
  hydration?: string
  caloriesEstimate?: number
  proteinEstimate?: number
}

interface CoachDietCopy {
  coachDietTitle: string
  coachDietBadge: string
  coachBreakfast: string
  coachLunch: string
  coachDinner: string
  coachSnacks: string
  coachHydration: string
  coachNotes: string
  coachCalories: string
  coachProtein: string
}

function CoachMealCard({ emoji, label, text, index }: { emoji: string; label: string; text: string; index: number }) {
  return (
    <motion.div
      className="rounded-[1.1rem] border border-white/60 bg-white/30 px-3.5 py-3"
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.05, duration: 0.22 }}
    >
      <div className="flex items-start gap-2.5">
        <span className="text-[16px] shrink-0 mt-0.5">{emoji}</span>
        <div className="min-w-0 flex-1">
          <h3 className="text-[10px] font-black uppercase tracking-[0.06em] text-[var(--guto-cyan)] mb-1">{label}</h3>
          <p className="text-[12px] leading-relaxed text-[var(--guto-navy)]/80 whitespace-pre-wrap">{text}</p>
        </div>
      </div>
    </motion.div>
  )
}

function CoachDietView({ coachDiet, copy }: { coachDiet: CoachDietDay; copy: CoachDietCopy }) {
  const meals = [
    { key: "breakfast", emoji: "☕", label: copy.coachBreakfast, text: coachDiet.breakfast },
    { key: "lunch", emoji: "🍽️", label: copy.coachLunch, text: coachDiet.lunch },
    { key: "dinner", emoji: "🌙", label: copy.coachDinner, text: coachDiet.dinner },
    { key: "snacks", emoji: "🍎", label: copy.coachSnacks, text: coachDiet.snacks },
  ].filter((m): m is { key: string; emoji: string; label: string; text: string } => Boolean(m.text))

  return (
    <div className="flex h-full min-h-0 flex-col">
      <div className="shrink-0 pb-2.5 pt-0.5 text-center">
        <h1 className="text-[1.1rem] font-black uppercase leading-tight tracking-[0.08em] text-[var(--guto-navy)]">
          {copy.coachDietTitle}
        </h1>
        <div className="mt-2 flex items-center justify-center">
          <span className="rounded-full bg-[rgba(82,231,255,0.13)] px-2 py-0.5 font-mono text-[7px] font-black uppercase tracking-[0.12em] text-[var(--guto-cyan)]">
            {copy.coachDietBadge}
          </span>
        </div>
      </div>

      {(coachDiet.caloriesEstimate || coachDiet.proteinEstimate) && (
        <motion.div
          className="shrink-0 mb-3 rounded-[1.1rem] border border-white/60 bg-white/30 flex items-center px-4 py-2.5"
          initial={{ opacity: 0, y: -6 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.28 }}
        >
          {coachDiet.caloriesEstimate && (
            <div className="flex flex-col items-center gap-0.5 flex-1">
              <Flame className="h-3 w-3 text-[var(--guto-cyan)]" />
              <span className="text-[14px] font-black leading-none text-[var(--guto-navy)]">{coachDiet.caloriesEstimate}</span>
              <span className="font-mono text-[7px] uppercase tracking-[0.1em] text-[rgba(13,35,65,0.38)] mt-0.5">{copy.coachCalories}</span>
            </div>
          )}
          {coachDiet.caloriesEstimate && coachDiet.proteinEstimate && (
            <div className="w-px h-6 bg-[rgba(13,35,65,0.07)]" />
          )}
          {coachDiet.proteinEstimate && (
            <div className="flex flex-col items-center gap-0.5 flex-1">
              <Zap className="h-3 w-3 text-[var(--guto-cyan)]" />
              <span className="text-[14px] font-black leading-none text-[var(--guto-navy)]">{coachDiet.proteinEstimate}g</span>
              <span className="font-mono text-[7px] uppercase tracking-[0.1em] text-[rgba(13,35,65,0.38)] mt-0.5">{copy.coachProtein}</span>
            </div>
          )}
        </motion.div>
      )}

      <div className="no-scrollbar min-h-0 flex-1 overflow-y-auto flex flex-col gap-2 pb-[calc(8rem+env(safe-area-inset-bottom))] overscroll-contain [scroll-padding-bottom:calc(8rem+env(safe-area-inset-bottom))] [-webkit-overflow-scrolling:touch]">
        {meals.map((m, i) => (
          <CoachMealCard key={m.key} emoji={m.emoji} label={m.label} text={m.text} index={i} />
        ))}

        {coachDiet.hydration && (
          <motion.div
            className="rounded-[1.1rem] border border-white/60 bg-white/30 px-3.5 py-3 flex items-start gap-2.5"
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: meals.length * 0.05, duration: 0.22 }}
          >
            <span className="text-[16px] shrink-0 mt-0.5">💧</span>
            <div className="min-w-0 flex-1">
              <h3 className="text-[10px] font-black uppercase tracking-[0.06em] text-[var(--guto-cyan)] mb-1">{copy.coachHydration}</h3>
              <p className="text-[12px] leading-relaxed text-[var(--guto-navy)]/80">{coachDiet.hydration}</p>
            </div>
          </motion.div>
        )}

        {coachDiet.notes && (
          <motion.div
            className="rounded-[1.1rem] border border-[rgba(82,231,255,0.25)] bg-[rgba(82,231,255,0.06)] px-3.5 py-3 flex items-start gap-2.5"
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: (meals.length + (coachDiet.hydration ? 1 : 0)) * 0.05, duration: 0.22 }}
          >
            <span className="text-[16px] shrink-0 mt-0.5">📋</span>
            <div className="min-w-0 flex-1">
              <h3 className="text-[10px] font-black uppercase tracking-[0.06em] text-[var(--guto-cyan)] mb-1">{copy.coachNotes}</h3>
              <p className="text-[12px] leading-relaxed text-[var(--guto-navy)]/80 italic">{coachDiet.notes}</p>
            </div>
          </motion.div>
        )}
      </div>
    </div>
  )
}

// ─── Main component ───────────────────────────────────────────────────────────

export function DietTab({ userId, language, onFoodDoubt, memory }: DietTabProps) {
  const validLang = getLanguage(language)
  const copy = dietCopy[validLang]

  const [plan, setPlan] = useState<DietPlan | null>(null)
  const [status, setStatus] = useState<"loading" | "generating" | "error" | "ready">("loading")
  const [errorMsg, setErrorMsg] = useState<string | null>(null)
  const [retrying, setRetrying] = useState(false)

  const weekDaysOrder = ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"] as const
  const todayCoachDiet = memory?.weeklyDietPlan?.days?.[weekDaysOrder[new Date().getDay()]] ?? null

  function isPlanStale(generatedAt: string): boolean {
    const planDate = new Date(generatedAt)
    const now = new Date()
    const lastSunday = new Date(now)
    lastSunday.setDate(now.getDate() - now.getDay())
    lastSunday.setHours(0, 0, 0, 0)
    return planDate < lastSunday
  }

  function isProfileComplete(): boolean {
    if (!memory) return false
    return Boolean(
      memory.heightCm && memory.heightCm > 0 &&
      memory.weightKg && memory.weightKg > 0 &&
      memory.trainingGoal &&
      memory.biologicalSex &&
      memory.userAge &&
      (memory.trainingLevel || memory.trainingStatus)
    )
  }

  useEffect(() => {
    if (!userId) return
    // If coach defined today's diet, skip API call
    if (todayCoachDiet) {
      setStatus("ready")
      return
    }
    let cancelled = false

    const hardTimeout = setTimeout(() => {
      if (!cancelled) {
        cancelled = true
        setStatus("error")
        setErrorMsg("Timeout: geração demorou demais. Tente novamente.")
      }
    }, 50_000)

    const run = async () => {
      setStatus("loading")
      setErrorMsg(null)
      try {
        let fetched = await getDietPlan()
        if (cancelled) return

        if (fetched && isPlanStale(fetched.generatedAt)) fetched = null

        if (!fetched) {
          setStatus("generating")
          fetched = await generateDietPlan(validLang)
          if (cancelled) return
        }

        setPlan(sanitizeDietPlan(fetched, memory, validLang))
        setStatus("ready")
      } catch (err: unknown) {
        if (cancelled) return
        setPlan(null)
        setStatus("error")
        if (!isMissingProfileError(err)) {
          setErrorMsg(getDietErrorMessage(err))
        }
      } finally {
        clearTimeout(hardTimeout)
      }
    }

    void run()
    return () => {
      cancelled = true
      clearTimeout(hardTimeout)
    }
  }, [userId, validLang, memory])

  const handleRetry = async () => {
    if (retrying) return
    if (plan?.lockedByCoach) {
      const confirmed = window.confirm(copy.lockedConfirm)
      if (!confirmed) return
    }
    setRetrying(true)
    setErrorMsg(null)
    try {
      const newPlan = await generateDietPlan(validLang)
      setPlan(sanitizeDietPlan(newPlan, memory, validLang))
      setStatus("ready")
    } catch (err: unknown) {
      setStatus("error")
      setErrorMsg(getDietErrorMessage(err))
    } finally {
      setRetrying(false)
    }
  }

  const retryLabel: Record<ValidLanguage, string> = {
    "pt-BR": "Falha ao gerar. Tente novamente.",
    "en-US": "Failed to generate. Try again.",
    "it-IT": "Errore nella creazione. Riprova.",
  }

  // ── Coach weekly diet takes priority over AI-generated plan ─────────────
  if (todayCoachDiet) {
    return <CoachDietView coachDiet={todayCoachDiet} copy={copy} />
  }

  // ── Loading / Generating ──────────────────────────────────────────────────
  if (status === "loading" || status === "generating") {
    return (
      <div className="flex h-full min-h-0 flex-col items-center justify-center gap-3">
        <motion.div
          animate={{ opacity: [0.4, 1, 0.4] }}
          transition={{ duration: 1.5, repeat: Infinity }}
          className="font-mono text-[10px] uppercase tracking-[0.22em] text-[var(--guto-cyan)]"
        >
          {copy.generatingLabel}
        </motion.div>
        {status === "generating" && (
          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.6 }}
            className="font-mono text-[8px] uppercase tracking-[0.14em] text-[rgba(13,35,65,0.35)] text-center max-w-[200px]"
          >
            {copy.generatingSubtitle}
          </motion.p>
        )}
      </div>
    )
  }

  // ── Empty / Error ─────────────────────────────────────────────────────────
  if (!plan) {
    const profileComplete = isProfileComplete()
    const bodyText = !profileComplete ? copy.emptyBody : errorMsg || retryLabel[validLang]

    return (
      <div className="flex h-full min-h-0 flex-col">
        <div className="shrink-0 pb-3 pt-1 text-center">
          <h1 className="text-[1.15rem] font-black uppercase leading-tight tracking-[0.08em] text-[var(--guto-navy)]">
            {copy.title}
          </h1>
        </div>
        <div className="flex-1 flex flex-col items-center justify-center gap-5 pb-4">
          <div className="relative w-20 h-20 flex items-center justify-center">
            <div className="absolute inset-0 rounded-full bg-[rgba(82,231,255,0.10)] blur-xl" />
            <motion.div
              animate={{ rotate: [0, 8, -8, 0], scale: [1, 1.04, 1] }}
              transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }}
              className="relative text-4xl"
            >
              🥗
            </motion.div>
          </div>
          <div className="text-center max-w-[240px]">
            <h2 className="text-[0.95rem] font-black uppercase leading-tight tracking-[0.06em] text-[var(--guto-navy)] mb-2">
              {copy.emptyTitle}
            </h2>
            <p className="text-[12px] leading-relaxed text-[rgba(13,35,65,0.60)]">{bodyText}</p>
          </div>
          {/* Students request diet changes via chat, not by regenerating directly */}
        </div>
      </div>
    )
  }

  // ── Plan view ─────────────────────────────────────────────────────────────
  const { macros, meals, generatedAt } = plan
  const goalName = copy.goalNames[macros.goal] || macros.goal
  const weekRange = getWeekRange(generatedAt, validLang)
  const planSourceLabel =
    plan.source === "coach_manual"
      ? copy.supervisorPlan
      : plan.source === "mixed"
        ? copy.mixedPlan
        : plan.source === "guto_generated"
          ? copy.gutoPlan
          : null

  return (
    <div className="flex h-full min-h-0 flex-col">

      {/* ── Header ── */}
      <div className="shrink-0 pb-2.5 pt-0.5 text-center">
        <h1 className="text-[1.1rem] font-black uppercase leading-tight tracking-[0.08em] text-[var(--guto-navy)]">
          {copy.title}
        </h1>
        <p className="font-mono text-[8px] uppercase tracking-[0.12em] text-[rgba(13,35,65,0.40)] mt-0.5">
          {weekRange}
        </p>
        {(planSourceLabel || plan.lockedByCoach) && (
          <div className="mt-2 flex flex-wrap items-center justify-center gap-1.5">
            {planSourceLabel && (
              <span className="rounded-full bg-[rgba(82,231,255,0.13)] px-2 py-0.5 font-mono text-[7px] font-black uppercase tracking-[0.12em] text-[var(--guto-cyan)]">
                {planSourceLabel}
              </span>
            )}
            {plan.lockedByCoach && (
              <span className="rounded-full bg-[rgba(13,35,65,0.08)] px-2 py-0.5 font-mono text-[7px] font-black uppercase tracking-[0.12em] text-[rgba(13,35,65,0.52)]">
                {copy.lockedPlan}
              </span>
            )}
          </div>
        )}
      </div>

      {/* ── Summary card ── */}
      <motion.div
        className="shrink-0 mb-3 rounded-[1.1rem] border border-white/60 bg-white/30"
        initial={{ opacity: 0, y: -6 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.28 }}
      >
        {/* Kcal row */}
        <div className="flex items-center justify-between px-4 pt-3 pb-2">
          <div className="flex items-end gap-1.5">
            <Flame className="h-4 w-4 text-[var(--guto-cyan)] mb-px shrink-0" />
            <span className="text-[24px] font-black leading-none text-[var(--guto-navy)]">
              {macros.targetKcal}
            </span>
            <div className="flex flex-col mb-0.5">
              <span className="font-mono text-[8px] leading-none text-[var(--guto-navy)]/40">kcal</span>
              <span className="font-mono text-[7px] leading-none text-[var(--guto-navy)]/30">{copy.perDay}</span>
            </div>
          </div>
          <span className="font-mono text-[8px] font-black uppercase tracking-[0.1em] text-[var(--guto-navy)] bg-[rgba(82,231,255,0.15)] px-2.5 py-1 rounded-full">
            {goalName}
          </span>
        </div>

        {/* Divider */}
        <div className="mx-4 h-px bg-[rgba(82,231,255,0.15)]" />

        {/* Macros row */}
        <div className="flex items-center px-4 py-2.5">
          <MacroPill icon={<Zap className="h-3 w-3" />} label={copy.proteinLabel} value={`${macros.proteinG}g`} color="cyan" />
          <div className="w-px h-6 bg-[rgba(13,35,65,0.07)]" />
          <MacroPill icon={<Wheat className="h-3 w-3" />} label={copy.carbsLabel} value={`${macros.carbsG}g`} color="amber" />
          <div className="w-px h-6 bg-[rgba(13,35,65,0.07)]" />
          <MacroPill icon={<Droplets className="h-3 w-3" />} label={copy.fatLabel} value={`${macros.fatG}g`} color="sky" />
        </div>
      </motion.div>

      {/* ── Scrollable meals ── */}
      <div className="no-scrollbar min-h-0 flex-1 overflow-y-auto flex flex-col gap-2 pb-[calc(8rem+env(safe-area-inset-bottom))] overscroll-contain [scroll-padding-bottom:calc(8rem+env(safe-area-inset-bottom))] [-webkit-overflow-scrolling:touch]">
        {meals.map((meal, i) => (
          <MealCard
            key={meal.id}
            meal={meal}
            onFoodDoubt={onFoodDoubt}
            index={i}
            foodQuestionLabel={copy.foodQuestionLabel}
          />
        ))}

        {/* Regenerate — subtle, at bottom */}
        <motion.button
          type="button"
          whileTap={{ scale: 0.97 }}
          onClick={() => { gutoAudio.playGutoFeedback('tap'); handleRetry() }}
          disabled={retrying}
          className="mt-1 flex items-center justify-center gap-2 w-full h-9 rounded-[0.85rem] border border-[rgba(82,231,255,0.25)] bg-transparent text-[var(--guto-cyan)]/60 font-mono text-[8px] font-black uppercase tracking-[0.14em] disabled:opacity-40"
        >
          <RefreshCw className="h-3 w-3" />
          {copy.regenerateButton}
        </motion.button>

        <p className="mt-2 text-center font-mono text-[7px] uppercase tracking-[0.1em] text-[rgba(13,35,65,0.30)] px-4">
          {copy.disclaimer}
        </p>
      </div>
    </div>
  )
}

// ─── MacroPill ─────────────────────────────────────────────────────────────────

function MacroPill({
  icon,
  label,
  value,
  color,
}: {
  icon: React.ReactNode
  label: string
  value: string
  color: "cyan" | "amber" | "sky"
}) {
  const colorMap = { cyan: "text-[var(--guto-cyan)]", amber: "text-amber-500", sky: "text-sky-400" }
  return (
    <div className="flex flex-col items-center gap-0.5 flex-1">
      <div className={colorMap[color]}>{icon}</div>
      <span className="text-[14px] font-black leading-none text-[var(--guto-navy)]">{value}</span>
      <span className="font-mono text-[7px] uppercase tracking-[0.1em] text-[rgba(13,35,65,0.38)] mt-0.5">{label}</span>
    </div>
  )
}
