import Link from "next/link"

type Lang = "pt-BR" | "en-US" | "it-IT"

type Section =
  | { heading: string; body: string }
  | { heading: string; privacyParts: [string, string] }

const VALID_LANGS: Lang[] = ["pt-BR", "en-US", "it-IT"]

const termsCopy: Record<Lang, {
  title: string
  heading: string
  version: string
  back: string
  privacyLink: string
  privacyHref: string
  sections: Section[]
}> = {
  "pt-BR": {
    title: "Termos de Uso — GUTO",
    heading: "Termos de Uso",
    version: "Versão beta — maio 2026",
    back: "Voltar ao GUTO",
    privacyLink: "Política de Privacidade",
    privacyHref: "/privacy?lang=pt-BR",
    sections: [
      { heading: "1. O que é o GUTO", body: "O GUTO é um assistente digital com inteligência artificial desenvolvido para apoiar treino, alimentação e rotina de evolução física. Ele é operado por Willian Gustavo dos Santos (contato: app.guto.life@gmail.com)." },
      { heading: "2. GUTO não é um profissional de saúde", body: "O GUTO não substitui médico, nutricionista, personal trainer ou qualquer profissional de saúde presencial. Tudo que o GUTO sugere — treinos, dietas, rotinas — é de natureza educacional e informativa, não constituindo prescrição médica ou nutricional." },
      { heading: "3. Responsabilidade do usuário", body: "Você é responsável por respeitar seus limites físicos. Se sentir dor, tontura, mal-estar ou tiver qualquer condição médica preexistente, interrompa o treino imediatamente e procure um profissional de saúde. Não ignore sinais do seu corpo." },
      { heading: "4. Versão beta", body: "O GUTO está em fase de beta privado. Isso significa que o sistema pode ter erros, instabilidades ou mudanças sem aviso prévio. Não garanta dependência crítica às informações geradas pelo GUTO neste período." },
      { heading: "5. Uso responsável", body: "Você concorda em usar o GUTO apenas para fins pessoais e legais. É proibido compartilhar acesso com terceiros sem autorização, tentar extrair ou reverter engenharia do sistema, ou usá-lo para fins que prejudiquem outros." },
      { heading: "6. Dados pessoais", privacyParts: ["O tratamento dos seus dados é descrito na ", ". Ao usar o GUTO, você concorda com esse tratamento."] },
      { heading: "7. Alterações nestes termos", body: "Estes termos podem ser atualizados durante o período beta. Mudanças significativas serão comunicadas diretamente no app. O uso continuado do GUTO após a notificação implica aceitação." },
      { heading: "8. Contato", body: "Para dúvidas sobre estes termos, entre em contato: app.guto.life@gmail.com" },
    ],
  },
  "en-US": {
    title: "Terms of Use — GUTO",
    heading: "Terms of Use",
    version: "Beta version — May 2026",
    back: "Back to GUTO",
    privacyLink: "Privacy Policy",
    privacyHref: "/privacy?lang=en-US",
    sections: [
      { heading: "1. What is GUTO", body: "GUTO is a digital assistant powered by artificial intelligence, developed to support training, nutrition, and physical evolution routines. It is operated by Willian Gustavo dos Santos (contact: app.guto.life@gmail.com)." },
      { heading: "2. GUTO is not a healthcare professional", body: "GUTO does not replace a doctor, nutritionist, personal trainer, or any in-person healthcare professional. Everything GUTO suggests — workouts, diets, routines — is educational and informational in nature and does not constitute medical or nutritional prescription." },
      { heading: "3. User responsibility", body: "You are responsible for respecting your physical limits. If you feel pain, dizziness, discomfort, or have any pre-existing medical condition, stop training immediately and seek a healthcare professional. Do not ignore your body's signals." },
      { heading: "4. Beta version", body: "GUTO is currently in private beta. This means the system may have errors, instabilities, or changes without prior notice. Do not rely critically on information generated by GUTO during this period." },
      { heading: "5. Responsible use", body: "You agree to use GUTO only for personal and lawful purposes. It is prohibited to share access with third parties without authorization, attempt to extract or reverse-engineer the system, or use it for purposes that harm others." },
      { heading: "6. Personal data", privacyParts: ["The handling of your data is described in the ", ". By using GUTO, you agree to this processing."] },
      { heading: "7. Changes to these terms", body: "These terms may be updated during the beta period. Significant changes will be communicated directly in the app. Continued use of GUTO after notification implies acceptance." },
      { heading: "8. Contact", body: "For questions about these terms, contact: app.guto.life@gmail.com" },
    ],
  },
  "it-IT": {
    title: "Termini di Utilizzo — GUTO",
    heading: "Termini di Utilizzo",
    version: "Versione beta — maggio 2026",
    back: "Torna a GUTO",
    privacyLink: "Informativa sulla Privacy",
    privacyHref: "/privacy?lang=it-IT",
    sections: [
      { heading: "1. Cos'è GUTO", body: "GUTO è un assistente digitale con intelligenza artificiale, sviluppato per supportare l'allenamento, l'alimentazione e le routine di evoluzione fisica. È gestito da Willian Gustavo dos Santos (contatto: app.guto.life@gmail.com)." },
      { heading: "2. GUTO non è un professionista sanitario", body: "GUTO non sostituisce un medico, un nutrizionista, un personal trainer o qualsiasi professionista sanitario in presenza. Tutto ciò che GUTO suggerisce — allenamenti, diete, routine — è di natura educativa e informativa, e non costituisce una prescrizione medica o nutrizionale." },
      { heading: "3. Responsabilità dell'utente", body: "Sei responsabile di rispettare i tuoi limiti fisici. Se senti dolore, vertigini, malessere o hai qualsiasi condizione medica preesistente, interrompi immediatamente l'allenamento e rivolgiti a un professionista sanitario. Non ignorare i segnali del tuo corpo." },
      { heading: "4. Versione beta", body: "GUTO è attualmente in fase di beta privata. Ciò significa che il sistema potrebbe avere errori, instabilità o modifiche senza preavviso. Non fare affidamento critico sulle informazioni generate da GUTO durante questo periodo." },
      { heading: "5. Uso responsabile", body: "Accetti di utilizzare GUTO solo per scopi personali e legali. È vietato condividere l'accesso con terzi senza autorizzazione, tentare di estrarre o decompilare il sistema, o utilizzarlo per scopi che danneggino altri." },
      { heading: "6. Dati personali", privacyParts: ["Il trattamento dei tuoi dati è descritto nell'", ". Usando GUTO, accetti questo trattamento."] },
      { heading: "7. Modifiche a questi termini", body: "Questi termini possono essere aggiornati durante il periodo beta. Le modifiche significative saranno comunicate direttamente nell'app. L'uso continuato di GUTO dopo la notifica implica l'accettazione." },
      { heading: "8. Contatto", body: "Per domande su questi termini, contatta: app.guto.life@gmail.com" },
    ],
  },
}

type Props = { searchParams: Promise<{ lang?: string }> }

export async function generateMetadata({ searchParams }: Props) {
  const { lang } = await searchParams
  const resolved: Lang = VALID_LANGS.includes(lang as Lang) ? (lang as Lang) : "pt-BR"
  return { title: termsCopy[resolved].title }
}

export default async function TermsPage({ searchParams }: Props) {
  const { lang } = await searchParams
  const resolved: Lang = VALID_LANGS.includes(lang as Lang) ? (lang as Lang) : "pt-BR"
  const t = termsCopy[resolved]

  return (
    <div className="h-full min-h-0 flex-1 overflow-y-auto overscroll-contain bg-white px-6 py-10 [-webkit-overflow-scrolling:touch]">
      <div className="mx-auto max-w-prose pb-[max(env(safe-area-inset-bottom),1.5rem)]">
        <p className="font-mono text-[10px] font-black uppercase tracking-[0.2em] text-[rgba(13,35,65,0.35)]">GUTO</p>
        <h1 className="mt-2 text-2xl font-black tracking-tight text-[rgba(13,35,65,0.9)]">{t.heading}</h1>
        <p className="mt-1 text-xs text-[rgba(13,35,65,0.4)]">{t.version}</p>

        <div className="mt-8 space-y-6 text-sm leading-relaxed text-[rgba(13,35,65,0.75)]">
          {t.sections.map((section) => (
            <section key={section.heading}>
              <h2 className="mb-2 font-mono text-[10px] font-black uppercase tracking-wider text-[rgba(13,35,65,0.55)]">
                {section.heading}
              </h2>
              {"privacyParts" in section ? (
                <p>
                  {section.privacyParts[0]}
                  <Link href={t.privacyHref} className="font-semibold underline text-[rgba(13,35,65,0.9)]">
                    {t.privacyLink}
                  </Link>
                  {section.privacyParts[1]}
                </p>
              ) : (
                <p>{section.body}</p>
              )}
            </section>
          ))}
        </div>

        <div className="mt-10 border-t border-[rgba(13,35,65,0.06)] pt-6">
          <Link
            href="/"
            className="font-mono text-[10px] font-black uppercase tracking-widest text-[rgba(13,35,65,0.4)] underline"
          >
            {t.back}
          </Link>
        </div>
      </div>
    </div>
  )
}
